### ISSUE TITLE
Integrate with tvrenamer?

### ISSUE THREAD

**Issue by eprenamer** [lsrom/tvmanager#1]
Hi, I saw that you had been active on tvrenamer/tvrenamer, and then ceased to be, so I clicked on your repositories and saw you decided to go off on your own.

The creators of tvrenamer have made me a maintainer, and I'm actively pushing stuff to it now.  I'd be happy to work with you if you have any interest in re-combining the projects.

**Comment by lsrom** [comment]
Hi,
yes I did create my own version but it is more for my self-education then
anything else. I would like to take part on tvrenamer but I went from
student to employee in the mean time so my time is not as free as it used
to be.

I will, however take a look at what you are doing over there and hopefully
join.

Thanks for thinking of me ;-)

**Comment by eprenamer** [comment]
No problem.  Even if you don't contribute code, perhaps you can help with testing.  I also have created a label "Help Requested" to highlight Issues to help is needed (and usually straightforward).
